/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlumnoRouteRouteImport } from './routes/alumno/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlumnoIndexRouteImport } from './routes/alumno/index'
import { Route as LoginMentorRouteImport } from './routes/login/mentor'
import { Route as LoginAlumnoRouteImport } from './routes/login/alumno'
import { Route as AlumnoTicketsRouteImport } from './routes/alumno/tickets'
import { Route as errors404RouteImport } from './routes/(errors)/404'

const AlumnoRouteRoute = AlumnoRouteRouteImport.update({
  id: '/alumno',
  path: '/alumno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoIndexRoute = AlumnoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlumnoRouteRoute,
} as any)
const LoginMentorRoute = LoginMentorRouteImport.update({
  id: '/login/mentor',
  path: '/login/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAlumnoRoute = LoginAlumnoRouteImport.update({
  id: '/login/alumno',
  path: '/login/alumno',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoTicketsRoute = AlumnoTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AlumnoRouteRoute,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRouteRouteWithChildren
  '/404': typeof errors404Route
  '/alumno/tickets': typeof AlumnoTicketsRoute
  '/login/alumno': typeof LoginAlumnoRoute
  '/login/mentor': typeof LoginMentorRoute
  '/alumno/': typeof AlumnoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof errors404Route
  '/alumno/tickets': typeof AlumnoTicketsRoute
  '/login/alumno': typeof LoginAlumnoRoute
  '/login/mentor': typeof LoginMentorRoute
  '/alumno': typeof AlumnoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRouteRouteWithChildren
  '/(errors)/404': typeof errors404Route
  '/alumno/tickets': typeof AlumnoTicketsRoute
  '/login/alumno': typeof LoginAlumnoRoute
  '/login/mentor': typeof LoginMentorRoute
  '/alumno/': typeof AlumnoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumno'
    | '/404'
    | '/alumno/tickets'
    | '/login/alumno'
    | '/login/mentor'
    | '/alumno/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/alumno/tickets'
    | '/login/alumno'
    | '/login/mentor'
    | '/alumno'
  id:
    | '__root__'
    | '/'
    | '/alumno'
    | '/(errors)/404'
    | '/alumno/tickets'
    | '/login/alumno'
    | '/login/mentor'
    | '/alumno/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumnoRouteRoute: typeof AlumnoRouteRouteWithChildren
  errors404Route: typeof errors404Route
  LoginAlumnoRoute: typeof LoginAlumnoRoute
  LoginMentorRoute: typeof LoginMentorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/alumno': {
      id: '/alumno'
      path: '/alumno'
      fullPath: '/alumno'
      preLoaderRoute: typeof AlumnoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumno/': {
      id: '/alumno/'
      path: '/'
      fullPath: '/alumno/'
      preLoaderRoute: typeof AlumnoIndexRouteImport
      parentRoute: typeof AlumnoRouteRoute
    }
    '/login/mentor': {
      id: '/login/mentor'
      path: '/login/mentor'
      fullPath: '/login/mentor'
      preLoaderRoute: typeof LoginMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/alumno': {
      id: '/login/alumno'
      path: '/login/alumno'
      fullPath: '/login/alumno'
      preLoaderRoute: typeof LoginAlumnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumno/tickets': {
      id: '/alumno/tickets'
      path: '/tickets'
      fullPath: '/alumno/tickets'
      preLoaderRoute: typeof AlumnoTicketsRouteImport
      parentRoute: typeof AlumnoRouteRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AlumnoRouteRouteChildren {
  AlumnoTicketsRoute: typeof AlumnoTicketsRoute
  AlumnoIndexRoute: typeof AlumnoIndexRoute
}

const AlumnoRouteRouteChildren: AlumnoRouteRouteChildren = {
  AlumnoTicketsRoute: AlumnoTicketsRoute,
  AlumnoIndexRoute: AlumnoIndexRoute,
}

const AlumnoRouteRouteWithChildren = AlumnoRouteRoute._addFileChildren(
  AlumnoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumnoRouteRoute: AlumnoRouteRouteWithChildren,
  errors404Route: errors404Route,
  LoginAlumnoRoute: LoginAlumnoRoute,
  LoginMentorRoute: LoginMentorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
