/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteRouteImport } from './routes/panel/route'
import { Route as AlumnoRouteRouteImport } from './routes/alumno/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as AlumnoIndexRouteImport } from './routes/alumno/index'
import { Route as PanelTicketsRouteImport } from './routes/panel/tickets'
import { Route as LoginMentorRouteImport } from './routes/login/mentor'
import { Route as LoginAlumnoRouteImport } from './routes/login/alumno'
import { Route as AlumnoTicketsRouteImport } from './routes/alumno/tickets'
import { Route as AlumnoSituacionRouteImport } from './routes/alumno/situacion'
import { Route as AlumnoRecursosRouteImport } from './routes/alumno/recursos'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as PanelEstudiantesStudentIdRouteImport } from './routes/panel/estudiantes/$studentId'

const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoRouteRoute = AlumnoRouteRouteImport.update({
  id: '/alumno',
  path: '/alumno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const AlumnoIndexRoute = AlumnoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlumnoRouteRoute,
} as any)
const PanelTicketsRoute = PanelTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => PanelRouteRoute,
} as any)
const LoginMentorRoute = LoginMentorRouteImport.update({
  id: '/login/mentor',
  path: '/login/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAlumnoRoute = LoginAlumnoRouteImport.update({
  id: '/login/alumno',
  path: '/login/alumno',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoTicketsRoute = AlumnoTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AlumnoRouteRoute,
} as any)
const AlumnoSituacionRoute = AlumnoSituacionRouteImport.update({
  id: '/situacion',
  path: '/situacion',
  getParentRoute: () => AlumnoRouteRoute,
} as any)
const AlumnoRecursosRoute = AlumnoRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => AlumnoRouteRoute,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelEstudiantesStudentIdRoute =
  PanelEstudiantesStudentIdRouteImport.update({
    id: '/estudiantes/$studentId',
    path: '/estudiantes/$studentId',
    getParentRoute: () => PanelRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRouteRouteWithChildren
  '/panel': typeof PanelRouteRouteWithChildren
  '/404': typeof errors404Route
  '/alumno/recursos': typeof AlumnoRecursosRoute
  '/alumno/situacion': typeof AlumnoSituacionRoute
  '/alumno/tickets': typeof AlumnoTicketsRoute
  '/login/alumno': typeof LoginAlumnoRoute
  '/login/mentor': typeof LoginMentorRoute
  '/panel/tickets': typeof PanelTicketsRoute
  '/alumno/': typeof AlumnoIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/estudiantes/$studentId': typeof PanelEstudiantesStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof errors404Route
  '/alumno/recursos': typeof AlumnoRecursosRoute
  '/alumno/situacion': typeof AlumnoSituacionRoute
  '/alumno/tickets': typeof AlumnoTicketsRoute
  '/login/alumno': typeof LoginAlumnoRoute
  '/login/mentor': typeof LoginMentorRoute
  '/panel/tickets': typeof PanelTicketsRoute
  '/alumno': typeof AlumnoIndexRoute
  '/panel': typeof PanelIndexRoute
  '/panel/estudiantes/$studentId': typeof PanelEstudiantesStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRouteRouteWithChildren
  '/panel': typeof PanelRouteRouteWithChildren
  '/(errors)/404': typeof errors404Route
  '/alumno/recursos': typeof AlumnoRecursosRoute
  '/alumno/situacion': typeof AlumnoSituacionRoute
  '/alumno/tickets': typeof AlumnoTicketsRoute
  '/login/alumno': typeof LoginAlumnoRoute
  '/login/mentor': typeof LoginMentorRoute
  '/panel/tickets': typeof PanelTicketsRoute
  '/alumno/': typeof AlumnoIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/estudiantes/$studentId': typeof PanelEstudiantesStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumno'
    | '/panel'
    | '/404'
    | '/alumno/recursos'
    | '/alumno/situacion'
    | '/alumno/tickets'
    | '/login/alumno'
    | '/login/mentor'
    | '/panel/tickets'
    | '/alumno/'
    | '/panel/'
    | '/panel/estudiantes/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/alumno/recursos'
    | '/alumno/situacion'
    | '/alumno/tickets'
    | '/login/alumno'
    | '/login/mentor'
    | '/panel/tickets'
    | '/alumno'
    | '/panel'
    | '/panel/estudiantes/$studentId'
  id:
    | '__root__'
    | '/'
    | '/alumno'
    | '/panel'
    | '/(errors)/404'
    | '/alumno/recursos'
    | '/alumno/situacion'
    | '/alumno/tickets'
    | '/login/alumno'
    | '/login/mentor'
    | '/panel/tickets'
    | '/alumno/'
    | '/panel/'
    | '/panel/estudiantes/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumnoRouteRoute: typeof AlumnoRouteRouteWithChildren
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
  errors404Route: typeof errors404Route
  LoginAlumnoRoute: typeof LoginAlumnoRoute
  LoginMentorRoute: typeof LoginMentorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumno': {
      id: '/alumno'
      path: '/alumno'
      fullPath: '/alumno'
      preLoaderRoute: typeof AlumnoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/alumno/': {
      id: '/alumno/'
      path: '/'
      fullPath: '/alumno/'
      preLoaderRoute: typeof AlumnoIndexRouteImport
      parentRoute: typeof AlumnoRouteRoute
    }
    '/panel/tickets': {
      id: '/panel/tickets'
      path: '/tickets'
      fullPath: '/panel/tickets'
      preLoaderRoute: typeof PanelTicketsRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/login/mentor': {
      id: '/login/mentor'
      path: '/login/mentor'
      fullPath: '/login/mentor'
      preLoaderRoute: typeof LoginMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/alumno': {
      id: '/login/alumno'
      path: '/login/alumno'
      fullPath: '/login/alumno'
      preLoaderRoute: typeof LoginAlumnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumno/tickets': {
      id: '/alumno/tickets'
      path: '/tickets'
      fullPath: '/alumno/tickets'
      preLoaderRoute: typeof AlumnoTicketsRouteImport
      parentRoute: typeof AlumnoRouteRoute
    }
    '/alumno/situacion': {
      id: '/alumno/situacion'
      path: '/situacion'
      fullPath: '/alumno/situacion'
      preLoaderRoute: typeof AlumnoSituacionRouteImport
      parentRoute: typeof AlumnoRouteRoute
    }
    '/alumno/recursos': {
      id: '/alumno/recursos'
      path: '/recursos'
      fullPath: '/alumno/recursos'
      preLoaderRoute: typeof AlumnoRecursosRouteImport
      parentRoute: typeof AlumnoRouteRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/estudiantes/$studentId': {
      id: '/panel/estudiantes/$studentId'
      path: '/estudiantes/$studentId'
      fullPath: '/panel/estudiantes/$studentId'
      preLoaderRoute: typeof PanelEstudiantesStudentIdRouteImport
      parentRoute: typeof PanelRouteRoute
    }
  }
}

interface AlumnoRouteRouteChildren {
  AlumnoRecursosRoute: typeof AlumnoRecursosRoute
  AlumnoSituacionRoute: typeof AlumnoSituacionRoute
  AlumnoTicketsRoute: typeof AlumnoTicketsRoute
  AlumnoIndexRoute: typeof AlumnoIndexRoute
}

const AlumnoRouteRouteChildren: AlumnoRouteRouteChildren = {
  AlumnoRecursosRoute: AlumnoRecursosRoute,
  AlumnoSituacionRoute: AlumnoSituacionRoute,
  AlumnoTicketsRoute: AlumnoTicketsRoute,
  AlumnoIndexRoute: AlumnoIndexRoute,
}

const AlumnoRouteRouteWithChildren = AlumnoRouteRoute._addFileChildren(
  AlumnoRouteRouteChildren,
)

interface PanelRouteRouteChildren {
  PanelTicketsRoute: typeof PanelTicketsRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelEstudiantesStudentIdRoute: typeof PanelEstudiantesStudentIdRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelTicketsRoute: PanelTicketsRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelEstudiantesStudentIdRoute: PanelEstudiantesStudentIdRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumnoRouteRoute: AlumnoRouteRouteWithChildren,
  PanelRouteRoute: PanelRouteRouteWithChildren,
  errors404Route: errors404Route,
  LoginAlumnoRoute: LoginAlumnoRoute,
  LoginMentorRoute: LoginMentorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
